placeholders:
    placeholders:
        view_navButtons_before:
            items:
                clever_age_customer_user_connect_as: ~
                commerce_customer_menu_button: ~
                commerce_customer_group_menu_button: ~
    items:
        clever_age_customer_user_connect_as:
            template: CleverAgeConnectAsBundle:Placeholders:connectAs.html.twig
            applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_customer.entity.customer_user.class%)"
